version: '#{build}'
image: 'Visual Studio 2019'
- provider: Environment
  name: production
  on:
    APPVEYOR_REPO_TAG: true

branches:
  only:
  - master
skip_tags: true
clone_depth: 1
build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_PREFIX_PATH=C:\Qt\5.13.1\msvc2017_64 ..
  - cmake --build . --config Release
artifacts:
- path: build/build/Release/RcloneBrowser.exe
test: off

deploy: off
#deploy:
#  release: "Rclone Browser $(APPVEYOR_REPO_TAG_NAME)"
#  description: 'Release description'
#  provider: GitHub
#  auth_token:
#    secure: r encrypted token> # your encrypted token from GitHub
#  artifact: /.*\.exe/            # upload all NuGet packages to release assets
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    APPVEYOR_REPO_TAG: true        # deploy on tag push only

